#!/usr/bin/env node
/* Generate public/fonts.css + public/fonts/ from @fontsource.
 *
 * WHY THIS EXISTS — the async-fonts delivery (Lighthouse-100 work, 2026-09):
 * webfont requests are issued at VeryHigh priority, and any font that finishes
 * before the first paint lands on Lighthouse's simulated FCP/LCP critical path
 * (~0.7s of simulated LCP on the homepage). Fonts never deserve that seat: the
 * fallback faces in tailwind.css are metric-compatible (size-adjust +
 * ascent/descent overrides), so first paint is geometry-identical and the
 * swap is invisible. The layout's boot script therefore injects
 * /fonts.css AFTER the first frame (double-rAF), which keeps every font
 * request out of the pre-paint window — locally, and through PSI against
 * production.
 *
 * The declarations here are BYTE-FAITHFUL to what the @fontsource imports
 * used to inline (same families, weights, styles, unicode-ranges, formats) —
 * only the delivery changed. Faces are read from the packages so a
 * `npm update` + rerun can never drift from the shipped font binaries.
 *
 * Run after changing font dependencies:  node scripts/sync-fonts.mjs
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

/* The exact css entries pages/layout.pyxl used to import. Order preserved —
 * it is the cascade order the site has always shipped. */
const ENTRIES = [
    '@fontsource-variable/ibm-plex-sans/index.css',
    '@fontsource/ibm-plex-mono/400.css',
    '@fontsource/ibm-plex-mono/400-italic.css',
    '@fontsource/ibm-plex-mono/500.css',
    '@fontsource/ibm-plex-mono/600.css',
];

const outDir = path.join(root, 'public', 'fonts');
fs.mkdirSync(outDir, { recursive: true });

let css = '/* GENERATED by scripts/sync-fonts.mjs — do not hand-edit.\n'
    + ' * Injected post-first-paint by the layout boot script (async fonts);\n'
    + ' * declarations mirror the @fontsource packages verbatim. */\n';
let copied = 0;

for (const entry of ENTRIES) {
    const entryPath = path.join(root, 'node_modules', entry);
    const entryDir = path.dirname(entryPath);
    let text = fs.readFileSync(entryPath, 'utf8');
    text = text.replace(/url\((\.\/files\/[^)]+)\)/g, (whole, rel) => {
        const source = path.resolve(entryDir, rel);
        const name = path.basename(source);
        fs.copyFileSync(source, path.join(outDir, name));
        copied += 1;
        return `url(/fonts/${name})`;
    });
    css += `\n/* ── ${entry} ── */\n${text}`;
}

fs.writeFileSync(path.join(root, 'public', 'fonts.css'), css);
const faces = (css.match(/@font-face/g) || []).length;
console.log(`✓ wrote public/fonts.css (${faces} faces) + ${copied} files in public/fonts/`);
